### ISSUE TITLE
Custom project frame text is not displaying

### ISSUE THREAD

**Issue by markshust** [mallowigi/material-theme-ui-lite#128]
**Describe the bug**
Custom project frame text is not displaying.

**To Reproduce**
1. Set custom text to `{file}`
2. Open file
<img width="1223" alt="Screenshot 2022-11-28 at 2 56 18 PM" src="https://user-images.githubusercontent.com/437029/204369081-23919485-e59d-491d-944c-802f4c572fb2.png">

**Expected Behavior**
1. The project frame text should be showing `template.js` in this screenshot:
<img width="1280" alt="Screenshot 2022-11-28 at 2 56 25 PM" src="https://user-images.githubusercontent.com/437029/204369057-e95302a1-24e6-4cfb-bd96-b79d26ddffac.png">

**Environment**
<img width="524" alt="Screenshot 2022-11-28 at 2 57 38 PM" src="https://user-images.githubusercontent.com/437029/204369144-19e1aabf-3387-44e9-917b-2c2bb21a8939.png">

Extra info:
* macOS 13.0.1
* PhpStorm 2022.3 RC
* Material Theme UI version 8.3.1

**Comment by mallowigi** [comment]
Weird, how is that possible? Is it on all windows ?

**Comment by markshust** [comment]
I'm on macOS Ventura 13.0.1

**Comment by markshust** [comment]
Odd, after a reboot it's back! I'll close this out unless it happens again.
