### ISSUE TITLE
Red line between editor tabs in Webstorm 2022.3

### ISSUE THREAD

**Issue by LukasAV** [mallowigi/material-theme-ui-lite#129]
Using Material Oceanic on Webstorm 2022.3 with the new UI results in a strange red line between split editor tabs
![image](https://user-images.githubusercontent.com/41890101/205101331-9e3f9948-4e8c-4232-a7df-9495f3c9de01.png)
This should be colored the same as the other separator lines, eg. between editor and tool window.

**Comment by mallowigi** [comment]
😳

Thanks for the report, I'll investigate
