### ISSUE TITLE
NightOwl - Current selected file in project tree difficult to identify

### ISSUE THREAD

**Issue by fools-mate** [mallowigi/material-theme-ui-lite#13]
It's very hard time to identify the current selected file in the project tree.
It seems the hex colors in the config file are a bit off.

Thank you for your time and effort!

![image](https://user-images.githubusercontent.com/34334994/78886660-e5d9eb80-7a5e-11ea-96f0-b71a3d603eb2.png)

https://github.com/mallowigi/material-theme-ui-lite/blob/0803d47d47f2f04f4fb1045ea382491a0de649bf/src/main/resources/themes/Night%20Owl.theme.json#L749-L752

**Comment by mallowigi** [comment]
that's true, but this is to contrast with the excluded color. Otherwise they would look too similar. Besides you have the tree indicator to help.

Cheers!

**Comment by fools-mate** [comment]
Maybe it could get the color from the current selected line like in the editor?

It's nearly impossible under bad lighting to identify this. The tree only helps with which folder you are in.

I really don't want to push you to something, but I think it's really an issue and could improve the accessibility a lot.

Best regards!

**Comment by mallowigi** [comment]
my bad, I was referring to the Material theme plugin, in the lite version the color is truly hard to see. I'll check the differences with the main plugin and push it onto the lite.

**Comment by fools-mate** [comment]
No problem, everyone makes mistakes.
Thanks a lot!
