### ISSUE TITLE
Add new {projectFilePath} option to Project Frame -> Customize Text

### ISSUE THREAD

**Issue by markshust** [mallowigi/material-theme-ui-lite#130]
**Describe the solution you'd like**
I'd like a new variable named `{projectFilePath}` added to the Project Frame -> Customize Text box.

<img width="1027" alt="Screenshot 2022-12-06 at 3 07 10 PM" src="https://user-images.githubusercontent.com/437029/206012191-c4262aeb-ddad-44b7-855f-88f30fb47127.png">

At the moment, the closest option is `{file}`, however with deeply nested files it is hard to know exactly where it is located.

**Describe alternatives you've considered**
The "Navigation Bar" supplies just about what I'd like, however it is hooked to this extra bar which requires additional padding.

<img width="1101" alt="Screenshot 2022-12-06 at 3 08 55 PM" src="https://user-images.githubusercontent.com/437029/206012562-da7f3e89-baec-41ca-a552-4f565743f04d.png">

Rather than it saying `config.php` in the title bar, I'd like it to say `app/etc/config.php`, since that is the actual location of the file in the project.

It may also be worth considering adding an additional option named `{fullFilePath}` which would provide the full path of the file on the filesystem.

**Comment by mallowigi** [comment]
Wrong repo

**Comment by markshust** [comment]
Closed in favor of https://github.com/mallowigi/material-theme-issues/issues/287
