### ISSUE TITLE
No Material Theme UI menu in 2022.3 and v19

### ISSUE THREAD

**Issue by jonbk** [mallowigi/material-theme-ui-lite#131]
**Describe the bug**
Settings menu is not showing Material Theme UI entry, settings likes compact tab and menu are not available anymore.

**To Reproduce**

1. Install PHPStorm 2022.3
2. Install Material Theme UI lite v19 plugin

**Expected Behavior**
Material Theme UI menu should be available ine IDE menu

**Environment**
PhpStorm 2022.3
Build #PS-223.7571.212, built on December 1, 2022
Licensed to xxxxxxxxxxxxxxxxxxxxxxx
Subscription is active until xxxxxxxxxxxxxxxxxxxxxx
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-53-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1964M
Cores: 8
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.mallowigi.idea (19.0.0)
    mobi.hsz.idea.gitignore (4.4.4)
    de.espend.idea.php.annotation (8.3.0)
    ru.adelf.idea.dotenv (2022.3)
    fr.adrienbrault.idea.symfony2plugin (2022.1.237)
    com.mallowigi (80.0.0)

Current Desktop: ubuntu:GNOME

**Screenshots**
![Screenshot from 2022-12-06 22-35-57](https://user-images.githubusercontent.com/29717277/206028904-c007a958-41e8-46b4-8a83-ff1f311b948c.png)

**Comment by mallowigi** [comment]
Material theme lite don't have settings. You are mistaking with the pro version.

**Comment by jonbk** [comment]
Before the update, I could select compact menu/tabs with the lite version :thinking:

**Comment by mallowigi** [comment]
You're mistaking it with the free version of the pro plugin. The lite never had settings whatsoever.

**Comment by jonbk** [comment]
ok then, sorry for mistaken the origin of the problem. Thanks.
