### ISSUE TITLE
Editor tabs height too big

### ISSUE THREAD

**Issue by Viciousu** [mallowigi/material-theme-ui-lite#133]
After installing new editor and plugin tab height became significantly bigger than in previous version
If I switch to default Rider theme the height is normal

Any Material theme:
![image](https://user-images.githubusercontent.com/4673120/207822887-b951dc52-f5ab-4b04-8e6e-b90091b117da.png)
Rider light theme:
![image](https://user-images.githubusercontent.com/4673120/207823004-b653b793-14c3-44ee-8cc1-04bee1b45895.png)

Material Theme UI Lite 19.0.0
JetBrains Rider 2022.3
Build #RD-223.7571.232, built on December 5, 2022
Runtime version: 17.0.5+1-b653.14 amd64

**Comment by mallowigi** [comment]
I will add a compact theme soon

**Comment by Viciousu** [comment]
Great, thanks for your work! Much appreciated.

**Comment by Viciousu** [comment]
Got it in Material Theme UI Lite 20.0.0, perfect!

**Comment by RoseChilds** [comment]
Hi,

I was just wondering, why does the compact version also change the height of the tabs in the file explorer?

v18.1.0 Moonlight Contrast:
![image](https://user-images.githubusercontent.com/78880286/209707995-7bf173aa-c8a8-4b85-a7d2-fc1eb2dd7b7e.png)
v20.0.0 Moonlight Contrast Compact:
![image](https://user-images.githubusercontent.com/78880286/209708165-37f4af2a-f44d-4538-bed3-31ec6f9c3549.png)

I'd just like the style of 18.1.0 back without having to stop updating the plugin. Any ideas?

**Comment by mallowigi** [comment]
This is the default line height of the native themes. People were complaining about the bigger line height in the past, so I supposed that with compact mode they wanted such line height. It will be a tad problematic to have so many configuration choices though, and I don't want to spend time on this plugin that doesn't give me income.

I'll upload a custom build with the non compact line height for now.

[Material Theme UI Lite-20.0.1.zip](https://github.com/mallowigi/material-theme-ui-lite/files/10310222/Material.Theme.UI.Lite-20.0.1.zip)

**Comment by RoseChilds** [comment]
I see. Thanks for the custom build :)
