### ISSUE TITLE
GitHub theme project view background make text hard to see

### ISSUE THREAD

**Issue by gythialy** [mallowigi/material-theme-ui-lite#14]
The background of the `External Libraries` section of the GitHub theme makes the text difficult to read. And the other light themes have more or less similar problems.

- macOS v10.15.4
- IntelliJ v2020.1 with Go Plugin v201.7223.82.165
- material-theme-ui-lite v10.0 with GitHub theme enabled

![Screen Shot 2020-05-19 at 10 11 10](https://user-images.githubusercontent.com/773400/82277462-7d195380-99ba-11ea-94d0-8e1f23c7f43c.png)

**Comment by mallowigi** [comment]
Can you check your File Colors (Settings > Appearance > File Colors)?

**Comment by gythialy** [comment]
I removed all the custom items in `File Colors` and everything works fine, thank you very much!

It's wired that I didn't add these configurations myself. Anyway, problem solved, thanks again.
