### ISSUE TITLE
Incorrect editor tabs height

### ISSUE THREAD

**Issue by LouisLecouturier** [mallowigi/material-theme-ui-lite#154]
**Describe the bug**

Editor tabs aren't taking the normal space (even when I'm not in compact mode)

<img width="1512" alt="image" src="https://github.com/mallowigi/material-theme-ui-lite/assets/71454059/956f7174-f867-4946-a1b9-3a3ec355900a">

**Expected Behavior**

Editor tabs should take the same height as this "Project title" container
<img width="309" alt="image" src="https://github.com/mallowigi/material-theme-ui-lite/assets/71454059/a7258066-faa4-40b0-81ed-febece455387">

**Environment**

OS : MacOS
IntelliJ Product : WebStorm 2023.2
Plugin Version : 21.0.0

```
WebStorm 2023.2
Build #WS-232.8660.143, built on July 21, 2023
Licensed to Louis Lecouturier
Subscription is active until June 20, 2024.
For educational use only.
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.new.tool.window.layout=true
    project.tree.structure.show.url=false
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
```

**Comment by mallowigi** [comment]
Right, it changed in 2023.2. I'll fix it when i have some time
