### ISSUE TITLE
Changes the font always back to the theme font, even when disabled

### ISSUE THREAD

**Issue by SteffoSpieler** [mallowigi/material-theme-ui-lite#157]
**Describe the bug**
Every now and then the toggle `Use color scheme font instead of the default` gets activated automatically, eventhough I disabled it multiple times already.

**To Reproduce**

1. Install theme
2. Disable `Use color scheme font instead of the default`
3. *Wait for Update / Random chance?*
4. See the font toggle reset again.

**Expected Behavior**
A user setting shouldn't be reset. Especially multiple times.

**Environment**

```
WebStorm 2023.2.1
Build #WS-232.9559.58, built on August 22, 2023
Licensed to <redacted>
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.github.lppedd.idea-conventional-commit (0.22.0)
    biz.elfuego.idea.issues.gitea (1.6)
    com.mallowigi.idea (22.0.0)
    com.intellij.apacheConfig (232.9559.62)
    net.vektah.codeglance2 (1.5.5)
    com.intellij.ideolog (222.1.0.0)
    com.intellij.kubernetes (232.9559.34)
    com.almightyalpaca.intellij.plugins.discord (1.11.0)
    com.mallowigi (93.0.1)
    zielu.gittoolbox (500.0.15+222)
    mobi.hsz.idea.gitignore (4.5.1)
```
**Screenshots**

![grafik](https://github.com/mallowigi/material-theme-ui-lite/assets/41108856/9f24268f-1792-4f7c-97f5-e70306d9a91a)

**Comment by mallowigi** [comment]
The plugin doesn't touch this toggle. It's probably something else. 

Have you checked with the plugin disabled?
