### ISSUE TITLE
Incompatible with newest Version 2020.3

### ISSUE THREAD

**Issue by fools-mate** [mallowigi/material-theme-ui-lite#20]
`Plugin 'Material Theme UI Lite' (version '10.2') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is WS-203.5981.135`

**Comment by Abdelraman** [comment]
waiting for this :)

**Comment by vdefranc** [comment]
Please let me know if there's anything I can do to help with this! :)

**Comment by anstarovoyt** [comment]
@mallowigi Hi! 2020.3 is released and there is no compatible version with the plugin.

**Comment by Abdelraman** [comment]
now working, thanks a lot 👍
