### ISSUE TITLE
Material oceanic autosuggest the foreground and background issue

### ISSUE THREAD

**Issue by Abdelraman** [mallowigi/material-theme-ui-lite#26]
Dears, Hope everything is fine, thanks for your great project. I got an issue with Material UI theme and decided to shift to Material UI lite, the issue appears when using oceanic theme the background and foreground of a selection are the same which makes it difficult to see the namespace of the autosuggested values.

After using the new phpstorm version 2020.3.2 the same issue occurs with Material UI Lite. is there any solution for that.

Thanks

**Comment by mallowigi** [comment]
Can you provide screenshots?

**Comment by Abdelraman** [comment]
yes sure, 
![Screenshot 2021-01-28 214111](https://user-images.githubusercontent.com/4821833/106189985-aaf1a180-61b1-11eb-8d98-32f0ca439d53.png)

**Comment by Abdelraman** [comment]
it used to be like this in older versions
![image](https://user-images.githubusercontent.com/4821833/106190308-281d1680-61b2-11eb-8241-823fd9fec268.png)

**Comment by Abdelraman** [comment]
waiting for you kind response :)

**Comment by mallowigi** [comment]
I'll try to take a look later tonight

**Comment by Abdelraman** [comment]
any updates concerning this :)

**Comment by mallowigi** [comment]
I've looked at it and can see it but so far I could not find the right property to change it. I have a lot of work outside of this so eventually I'll get to it. Stay in touch.

**Comment by Abdelraman** [comment]
Thanks a lot for your efforts, I managed to solve it temporarily by using custom theme and change the selection background and secondary text color.
