### ISSUE TITLE
Cannot set any themes

### ISSUE THREAD

**Issue by bellus93** [mallowigi/material-theme-ui-lite#28]
In WebStorm EAP 2021.1

Cannot set Material Oceanic theme:
Do not request resource from classloader using path with leading slash (path=/walls/oceanic.svg)

Cannot set Atom One Dark theme:
Do not request resource from classloader using path with leading slash (path=/walls/onedark.svg)

Cannot set Dracula theme:
Do not request resource from classloader using path with leading slash (path=/walls/dracula.svg)

**Comment by mallowigi** [comment]
Thanks. FIxing that asap.

**Comment by mallowigi** [comment]
A fix has been released. There were a problem with wallpapers so I removed them temporarily.

Please check 13.1

**Comment by bellus93** [comment]
Now it works, thanks.
