### ISSUE TITLE
Transparent whitespace & WebStorm & Atom One Dark Theme 

### ISSUE THREAD

**Issue by Livitan** [mallowigi/material-theme-ui-lite#30]
Hello, thanks for your work!

 **WebStorm 
Atom One Dark Theme 
Transparent whitespace**

Can we have same color whitespace like in VS Code?

### **WebStorm** vs **VS Code**  font size 30px
![dDyzF3GkJV](https://user-images.githubusercontent.com/13551558/109687629-1bfaef00-7b8c-11eb-9403-4dccd12ae0d0.jpg)

### **WebStorm** font size 16px
![QqqhF6qq2m](https://user-images.githubusercontent.com/13551558/109687597-156c7780-7b8c-11eb-91b9-67ef3c91c9a2.jpg)

**Comment by mallowigi** [comment]
It depends on the theme. Which theme is it?

**Comment by Livitan** [comment]
Thank you for the fast answer @mallowigi !
Yes, that's right, on VS Code I use a different theme (One Dark Pro)
They look so identical that I thought they were the same thing.

I would be very grateful if you make a similar contrast for whitespace, so they can be seen with a font size of 16 pixels in the editor.
Or some way that I could do it myself.

**Comment by mallowigi** [comment]
Sure, if you know what the color is you can try to make a PR. Otherwise I'll get to it ASAP.
