### ISSUE TITLE
Autosuggest selection background disappears after switching down to next option 

### ISSUE THREAD

**Issue by Querschlag** [mallowigi/material-theme-ui-lite#37]
I can reproduce the effect with the Github and Material themes. A theme that is not affected: "Arc Dark"

<img width="869" alt="Screen Shot 2021-05-12 at 08 15 38" src="https://user-images.githubusercontent.com/1651468/117928214-84d4b500-b2fb-11eb-9bfa-91ac9c1b8a24.png">
<img width="878" alt="Screen Shot 2021-05-12 at 08 15 46" src="https://user-images.githubusercontent.com/1651468/117928217-8605e200-b2fb-11eb-8cfd-a41f6e8016b8.png">

**Comment by mallowigi** [comment]
This is related to https://github.com/mallowigi/material-theme-ui-lite/issues/26 but apparently the background color for the completion popup is now taken from the color schemes, so there's a bit tweaking to do. Thanks for the update.
