### ISSUE TITLE
Focus background colour is wrong on Tips dropdown in dark themes in WebStorm

### ISSUE THREAD

**Issue by blkvcv** [mallowigi/material-theme-ui-lite#38]
When dropdown appears, the first element is focused with the correct background colour - I can clearly distinguish it from other elements in the list.

![image](https://user-images.githubusercontent.com/29228048/118098829-b2416180-b3d4-11eb-84aa-b4ad98872440.png)

However, when I navigate thorough the list, background on the focused element is the same as the other elements in the list (but focus itself works fine, I see whole text where ellipsis was before)

![image](https://user-images.githubusercontent.com/29228048/118099299-53301c80-b3d5-11eb-9b1c-7a0bd197f276.png)

This is Deep Ocean Theme, and It doesn't work also with GitHub Dark Theme (and possibly with others, I only use Deep Ocean Theme).

However, when I switch f.e. to Monokai theme, I see that the first element when the dropdown appears is lighter

![image](https://user-images.githubusercontent.com/29228048/118099949-321bfb80-b3d6-11eb-94bf-022b28952009.png)

But when I start navigating, the colour changes to darker - the colour of the editor.
With those dark themes the colour of the editor and dropdown elements is the same, so there is no contrast.

![image](https://user-images.githubusercontent.com/29228048/118100002-42cc7180-b3d6-11eb-8e7e-1c3f5c435dcc.png)

So maybe it is just about the defining those colours better.
I tried to find whether I can change it myself in WebStorm, but didn't succeed.

As I'm using the tips all the time, this is a bit frustrating. Do you thing the bug is in the plugin or somewhere on my side?

**Comment by mallowigi** [comment]
This is something relatively new from a poll, which is using darker contrast to highlight the current choice rather than lighter as it always was. This is also what's happening in vscode.

More info here https://github.com/ChrisRM/material-theme-jetbrains/issues/1749

**Comment by mallowigi** [comment]
By the way if the color of the completion popup doesn't suit you, you can change it in the color scheme settings by looking at the property "documentation"

**Comment by blkvcv** [comment]
Thank you! I set it to the lighter colour so the focus is visible now.
