### ISSUE TITLE
Checkboxes in all dark theme are indistinguishable between states

### ISSUE THREAD

**Issue by DevCharly** [mallowigi/material-theme-ui-lite#39]
In version 15.0, the unselected checkboxes are filled in all dark themes.
IMHO it would be better to fill only selected checkboxes as in the light themes (see issue #29)

![image](https://user-images.githubusercontent.com/5604048/118109650-c3449f80-b3e1-11eb-8098-1cea8efeab2f.png)

![image](https://user-images.githubusercontent.com/5604048/118109666-c8095380-b3e1-11eb-88a4-05b9977bde39.png)

In the light themes, only the selected checkboxes are filled:

![image](https://user-images.githubusercontent.com/5604048/118109826-f8e98880-b3e1-11eb-9a9e-0bd0b1b84be6.png)

**Comment by mallowigi** [comment]
Just found out that the checkbox background color for dark themes use the same color for both selected and not selected. So there are two options available: either like this one, e.g. black on accent; or the opposite: accent on black
