### ISSUE TITLE
SciView: index cells do not align with data rows for pandas DataFrames

### ISSUE THREAD

**Issue by blair-anson** [mallowigi/material-theme-ui-lite#55]
**Describe the bug**
The index and value rows do not align. See the attached picture

**To Reproduce**
1. Upgraded to a recent version of the plugin

**Expected Behavior**
The index and value rows should be the same height.
If I switch to a standard pycharm theme the issue disappears

**Environment**
* Ubuntu 16.04
* PyCharm 2021.1.3 (Professional Edition) Build #PY-211.7628.24, built on June 30, 2021
* Material Theme UI Lite: 15.1

**Screenshots**
![image](https://user-images.githubusercontent.com/5399102/124723579-2b2ce780-df46-11eb-8e0a-10fc1ab30a94.png)

**Comment by mallowigi** [comment]
It's a known issue and not something that can be fix unfortunately. You can enable compact table cells and compact drop downs for a workaround

**Comment by blair-anson** [comment]
@mallowigi thanks. I am having trouble finding those settings in PyCharm. Can you please let me know where I can find them?

**Comment by mallowigi** [comment]
https://www.material-theme.com/docs/configuration/compact-settings/
