### ISSUE TITLE
Solarized Light Theme checkboxes show no mark inside; Oceanic Theme does

### ISSUE THREAD

**Issue by dennismayr** [mallowigi/material-theme-ui-lite#7]
I've found a small quirk in the Solarized Light theme:

Checkboxes only show borders when selected, and become a borderless white square when deselected.

- Expected behavior:
  A marked checkbox shows its border and an inner symbol in accent colors:
  Selected: [x]
  Deselected: [ ]

- What happens:
  Selected: [ ] (only the border in the accent color)
  Deselected: 
  (nothing)

OS: _elementaryOS 5.0 Juno / Ubuntu 18.04_
IntelliJ IDEA version: _2019.3.1_

**Comment by mallowigi** [comment]
It's actually the case for all light themes. Thanks.

**Comment by mallowigi** [comment]
It should be fixed in latest release
